import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Schema as MongooseSchema } from 'mongoose';

export enum UserRole {
  STUDENT = 'student',
  LANDLORD = 'landlord',
  FOOD_PROVIDER = 'food_provider',
  ADMIN = 'admin',
}

export enum IdentificationType {
  CNIC = 'cnic',
  PASSPORT = 'passport',
}

export enum SocialProvider {
  EMAIL = 'email',
  FACEBOOK = 'facebook',
  GOOGLE = 'google',
}

@Schema({ timestamps: true })
export class User extends Document {
  @Prop({ required: true })
  name: string;

  @Prop({ required: true, unique: true })
  email: string;

  @Prop({ required: true })
  password: string; // Plain text password as per requirement

  @Prop({ required: true, enum: UserRole, default: UserRole.STUDENT })
  role: UserRole;

  @Prop({ required: true })
  phone: string;

  @Prop({ required: true })
  countryCode: string; // Country code for phone number

  @Prop()
  address: string;

  @Prop({ required: true })
  gender: string;

  @Prop()
  profileImage?: string; // URL to profile image

  @Prop({ enum: IdentificationType })
  identificationType?: IdentificationType; // CNIC or Passport

  @Prop()
  identificationNumber?: string; // CNIC or Passport number

  // Social login fields
  @Prop()
  facebookId?: string; // Facebook user ID

  @Prop()
  googleId?: string; // Google user ID

  @Prop({ enum: SocialProvider, default: SocialProvider.EMAIL })
  socialProvider: SocialProvider; // Login method used

  @Prop({ default: false })
  isEmailVerified: boolean; // Email verification status

  @Prop({ default: true })
  isActive: boolean;

  // Authentication tracking
  @Prop({ default: 0 })
  failedLoginAttempts: number;

  @Prop()
  lastLoginAt?: Date;

  // Account deactivation tracking
  @Prop()
  deactivatedAt?: Date;

  @Prop({ type: MongooseSchema.Types.ObjectId, ref: 'User' })
  deactivatedBy?: string;

  @Prop()
  deactivationReason?: string;

  // FCM tokens for push notifications
  @Prop({ type: [String], default: [] })
  fcmTokens: string[];

  // Timestamps (auto-generated by mongoose)
  createdAt?: Date;
  updatedAt?: Date;
}

export const UserSchema = SchemaFactory.createForClass(User);
